//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dieseltech.Models
{
    using System;
    
    public partial class Sp_Get_LoadDetails_Result2
    {
        public string LoaderNumber { get; set; }
        public string Agent { get; set; }
        public string Branch { get; set; }
        public string Profile { get; set; }
        public string BrokerName { get; set; }
        public string CarrierName { get; set; }
        public string LoadTypeName { get; set; }
        public int NoOfPickups { get; set; }
        public string PickupLocation { get; set; }
        public string PickupDate { get; set; }
        public int NoOfDeliveries { get; set; }
        public string DeliveryLocation { get; set; }
        public string DeliveryDate { get; set; }
        public Nullable<int> BrokerRate { get; set; }
        public int CarrierRate { get; set; }
        public Nullable<int> Profit { get; set; }
    }
}
