//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dieseltech.Models
{
    using System;
    
    public partial class Sp_Get_Truck_List_Result3
    {
        public int TruckId { get; set; }
        public string TruckName { get; set; }
        public int Driverid { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsActive { get; set; }
        public string DriverName { get; set; }
        public Nullable<int> CarrierId { get; set; }
        public Nullable<int> ZoneId { get; set; }
        public string CarrierName { get; set; }
        public string ZoneName { get; set; }
    }
}
