//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dieseltech.Models
{
    using System;
    
    public partial class Sp_Get_LoadDetails_Result1
    {
        public int LoaderHeadId { get; set; }
        public string LoaderNumber { get; set; }
        public Nullable<int> CarrierId { get; set; }
        public Nullable<int> CarrierHelperId { get; set; }
        public string NumberToText { get; set; }
        public Nullable<bool> IsSendText { get; set; }
        public int TruckId { get; set; }
        public int CarrierRate { get; set; }
        public int LoadTypeId { get; set; }
        public string Commodity { get; set; }
        public int LoadSubTypeId { get; set; }
        public Nullable<int> Available { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> QuantityTypeId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public int DriverTypeId { get; set; }
        public string CarrierInstructions { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> BrokerId { get; set; }
        public Nullable<int> BrokerHelperId { get; set; }
        public Nullable<int> BrokerRate { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public string Extension { get; set; }
        public string ContactEmail { get; set; }
        public string BrokerReference { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<int> AgentGross { get; set; }
        public Nullable<int> AgentFlat { get; set; }
        public Nullable<int> BranchFlat { get; set; }
    }
}
