//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dieseltech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAgentcommission
    {
        public int AgentCommissionId { get; set; }
        public int AgentId { get; set; }
        public int Commissionpercentage { get; set; }
        public int salary { get; set; }
    }
}
