//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dieseltech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBroker
    {
        public int Brokerid { get; set; }
        public string Name { get; set; }
        public string MC { get; set; }
        public string AssignID { get; set; }
        public string ContactName { get; set; }
        public string Phone { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsActive { get; set; }
        public string Email { get; set; }
        public string AccountingEmail { get; set; }
    }
}
