//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dieseltech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCarrier
    {
        public int CarrierID { get; set; }
        public string CarrierName { get; set; }
        public string MC_ { get; set; }
        public string AssignID { get; set; }
        public string ContactName { get; set; }
        public string Phonenumber { get; set; }
        public Nullable<int> CarrierCategoryId { get; set; }
        public Nullable<int> IsOwnerOperator { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Comment { get; set; }
        public string PrefferedDestination { get; set; }
        public string Email { get; set; }
        public string ContactName2 { get; set; }
        public string Phonenumber2 { get; set; }
        public int IsQuickPay { get; set; }
        public Nullable<System.DateTime> InsuranceExpirationDate { get; set; }
        public int IsBlackList { get; set; }
        public double Quickpaypercentage { get; set; }
        public int Istrailerinterchange { get; set; }
        public int Isdeleted { get; set; }
        public Nullable<bool> IsNeedToAssign { get; set; }
    }
}
