//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dieseltech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompany
    {
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public int IsActive { get; set; }
        public int User_ID { get; set; }
        public System.DateTime Create_Date { get; set; }
    }
}
