//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dieseltech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCarrierDocument
    {
        public int CarrierDocumentId { get; set; }
        public string CarrierAssignId { get; set; }
        public Nullable<int> IsMcAuthorityUploaded { get; set; }
        public string McAuthorityFileName { get; set; }
        public string McAuthorityFilePath { get; set; }
        public Nullable<int> IsW9Uploaded { get; set; }
        public string W9FileName { get; set; }
        public string W9FilePath { get; set; }
        public Nullable<int> IsInsuranceUploaded { get; set; }
        public string InsuranceFileName { get; set; }
        public string InsuranceFilePath { get; set; }
        public string UploadedBy { get; set; }
        public Nullable<System.DateTime> UploadedDate { get; set; }
        public Nullable<int> IsNoticeOfAssignment { get; set; }
        public string AssignmentFileName { get; set; }
        public string AssignmentFilePath { get; set; }
        public Nullable<int> IsVoidCheque { get; set; }
        public string VoidChequeFileName { get; set; }
        public string VoidChequeFilePath { get; set; }
    }
}
