//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dieseltech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDriverLicense
    {
        public int DriverLicenseID { get; set; }
        public string CarrierAssignId { get; set; }
        public Nullable<int> TruckId { get; set; }
        public Nullable<int> IsDriverLicenseUploaded { get; set; }
        public string LicenseFileName { get; set; }
        public string LicenseFilePath { get; set; }
        public string UploadedBy { get; set; }
        public Nullable<System.DateTime> UploadedDate { get; set; }
        public Nullable<int> DriverId { get; set; }
    }
}
