//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dieseltech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLoadPickupDelivery
    {
        public int PickupDeliveryId { get; set; }
        public string LoaderNumber { get; set; }
        public string Information { get; set; }
        public string StatusFlague { get; set; }
        public Nullable<int> ShipperId { get; set; }
        public string ShipperName { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> StateId { get; set; }
        public string ZipCode { get; set; }
        public Nullable<System.DateTime> DateTimeFrom { get; set; }
        public Nullable<System.DateTime> DateTimeTo { get; set; }
        public string AppointmentNumber { get; set; }
        public string Traitor { get; set; }
        public string Comments { get; set; }
    }
}
