//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dieseltech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLoadDelivery
    {
        public int DeliveryId { get; set; }
        public int PickUpId { get; set; }
        public string LoadNumber { get; set; }
        public string Information { get; set; }
        public int ShipperId { get; set; }
        public string ShipperName { get; set; }
        public int CountryId { get; set; }
        public string CountryName { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public string ZipCode { get; set; }
        public string StateCode { get; set; }
        public string CityName { get; set; }
        public System.DateTime DateTimeFrom { get; set; }
        public System.DateTime DateTimeTo { get; set; }
        public string PickupNumber { get; set; }
        public string Traitor { get; set; }
        public string Comments { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int IsSave { get; set; }
        public int MaxDeliveryID { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public int Deliveryorder { get; set; }
        public string NewDateFrom { get; set; }
        public string NewDateTo { get; set; }
    }
}
