//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dieseltech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLoadHead
    {
        public int LoaderHeadId { get; set; }
        public string LoaderNumber { get; set; }
        public string CarrierId { get; set; }
        public string NumberToText { get; set; }
        public Nullable<bool> IsSendText { get; set; }
        public int TruckId { get; set; }
        public decimal CarrierRate { get; set; }
        public int LoadTypeId { get; set; }
        public string Commodity { get; set; }
        public int LoadSubTypeId { get; set; }
        public Nullable<int> Available { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> QuantityTypeId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public int DriverTypeId { get; set; }
        public string CarrierInstructions { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string BrokerId { get; set; }
        public Nullable<decimal> BrokerRate { get; set; }
        public string Extension { get; set; }
        public string BrokerReference { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<decimal> AgentGross { get; set; }
        public Nullable<int> AgentFlat { get; set; }
        public Nullable<int> BranchFlat { get; set; }
        public Nullable<int> IsPrint { get; set; }
        public Nullable<int> IsBrokerConfirm { get; set; }
        public Nullable<int> IsCarrierConfirm { get; set; }
        public Nullable<int> IsPod { get; set; }
        public Nullable<int> IsLumper { get; set; }
        public Nullable<int> IsMarkCOD { get; set; }
        public string Comment { get; set; }
        public string DispatcherName { get; set; }
        public string DispatcherPhone { get; set; }
        public string DriverName { get; set; }
        public string DriverPhone { get; set; }
        public Nullable<int> IsCancel { get; set; }
        public Nullable<int> BrokerAmout { get; set; }
        public Nullable<int> CarrierAmount { get; set; }
        public Nullable<bool> IsFutureLoad { get; set; }
        public string FutureLoadText { get; set; }
        public Nullable<int> IsInvoiceCustomer { get; set; }
        public Nullable<int> IsPaymentRecieved { get; set; }
        public Nullable<int> IsPaidCarrier { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> IsFuelAdvance { get; set; }
        public Nullable<int> FuelAdvanceAmount { get; set; }
        public string InvoiceNumber { get; set; }
        public int IsQuickPay { get; set; }
        public decimal QuickPaypercentage { get; set; }
        public decimal AdjustedCarrierRate { get; set; }
        public Nullable<bool> IsManagerFutureLoad { get; set; }
    }
}
