//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dieseltech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNotification
    {
        public int NotificationId { get; set; }
        public string NotificationType { get; set; }
        public string NotificationTypeReference { get; set; }
        public int IsRead { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string NotificationReferenceName { get; set; }
        public System.DateTime InsuranceExpirationDate { get; set; }
        public int CompanyId { get; set; }
    }
}
