//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dieseltech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProfile
    {
        public int profile_id { get; set; }
        public string Profile_name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string phoneNo { get; set; }
        public string youtube { get; set; }
        public string instagram { get; set; }
        public string Linkdin { get; set; }
        public string Twitter { get; set; }
        public string Facebook { get; set; }
        public string Details { get; set; }
        public string Designation { get; set; }
        public string Image { get; set; }
        public Nullable<int> IsActive { get; set; }
        public string Adress { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<int> Packageid { get; set; }
        public Nullable<int> Accessid { get; set; }
        public int Isdeleted { get; set; }
        public Nullable<int> AgentTierId { get; set; }
    }
}
