//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dieseltech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblShipper
    {
        public int ShipperId { get; set; }
        public string ShipperName { get; set; }
        public string ShipperPhone { get; set; }
        public string ShipperAddress { get; set; }
        public string ShipperCity { get; set; }
        public string ShipperStateCode { get; set; }
        public string ShipperStateName { get; set; }
        public Nullable<int> ShipperZipCode { get; set; }
        public string ShipperAssignId { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
    }
}
